--  OVERALL PLAN
-- 1. Load in the .json file with the positions of each joint
-- 2. Calculate the length and angle of the lower arm
-- 3. Generate a list of lower arm anagle that the characterisitics should be generated at from full
--      compression (bumps stop angle) to full drop (limit strap angle) which should be inputs from the user.
-- 4. run each angle through the calculator and store the results in a new list of outputs
-- 5. save each output to a csv file that can be looked at later.
